name: Build YOLO Inspector

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./radar-vision-identify-ai/vision-detect-check
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yolo-inspector:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/yolo-inspector:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
